# Generated by Django 4.1.6 on 2023-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Exchange", models.CharField(blank=True, max_length=100, null=True)),
                ("Symbol", models.CharField(blank=True, max_length=100, null=True)),
                ("Shortname", models.CharField(blank=True, max_length=250, null=True)),
                ("Longname", models.CharField(blank=True, max_length=250, null=True)),
                ("Sector", models.CharField(blank=True, max_length=250, null=True)),
                ("Industry", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "Currentprice",
                    models.FloatField(blank=True, max_length=250, null=True),
                ),
                (
                    "Marketcap",
                    models.IntegerField(blank=True, max_length=250, null=True),
                ),
                ("Ebitda", models.IntegerField(blank=True, max_length=250, null=True)),
                (
                    "Revenuegrowth",
                    models.FloatField(blank=True, max_length=50, null=True),
                ),
                ("City", models.CharField(blank=True, max_length=100, null=True)),
                ("State", models.CharField(blank=True, max_length=50, null=True)),
                ("Country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Fulltimeemployees",
                    models.IntegerField(blank=True, max_length=50, null=True),
                ),
                (
                    "Longbusinesssummary",
                    models.IntegerField(blank=True, max_length=2000, null=True),
                ),
                ("Weight", models.FloatField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
