# Generated by Django 4.1.6 on 2023-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_company_longbusinesssummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="Currentprice",
            field=models.FloatField(
                blank=True, default=None, max_length=250, null=True
            ),
        ),
    ]
