# Generated by Django 4.1.6 on 2023-02-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_currentprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="Currentprice",
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
    ]
